name: frontend app

on:
  push:
    branches: [ "main" ]
    paths:
        - 'frontend/**'

jobs:
    
    build_frontend_app:

        name: build frontend app
        runs-on: ubuntu-latest

        steps:
            - name: checkout frontend dir as root dir
              uses: actions/checkout@v3

            - name: install node js
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
                cache: 'npm'
                cache-dependency-path: frontend/package-lock.json
            
            - name: install packages and build app
              run: |
                cd frontend
                npm ci
                npm run build

            # - name: checkout dir
            #   uses: actions/checkout@v3

            # - name: caching docker build
            #   uses: actions/cache@v3
            #   with:
            #     path: var/lib/docker
            #     key: ${{runner.os}}-docker-${{hashFiles('**/multistage.Dockerfile')}}
            #     restore-keys: ${{runner.os}}-docker-

            - name: login docker
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASS }}
            
            - name: build and push
              uses: docker/build-push-action@v4
              with:
                context: ./frontend
                file: ./frontend/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/frontend_app:v${{ github.run_number }}